using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SupportApp.Models
{
    public class Comment: AuditObj
    {
        //event id is generated by the ICollection of Event
        public int Id { get; set; }
        [Required(ErrorMessage = "Message is required")]
        public string Message { get; set; }

        public string ApplicationUserId { get; set; }
        ////this will help finding the applicationUser first name without doing a separate query
        //[ForeignKey("ApplicatinoUserId")]
        //public ApplicationUser ApplicationUser { get; set; }
    }
}
